version: '3.1'  # Versión de Docker Compose

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Nombre de usuario del administrador
      MONGO_INITDB_ROOT_PASSWORD: example  # Contraseña del administrador
    volumes:
      - mongodb_data:/data/db  # Persistir los datos incluso después de que el contenedor se detenga
  https-server:
    image: nginx
    ports:
      - "9443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/nginx/cert.pem:ro
      - ./webmedia:/usr/share/nginx/html:ro
      - ./key.pem:/etc/nginx/key.pem:ro
  sisflix:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./sisflix:/usr/src/app
    environment:
      - NODE_ENV=production

    command: sh -c "npm install && npm start"
    depends_on:
      - mongo 
    ports:
      - "8443:443"



volumes:
  mongodb_data:  # Define un volumen para la persistencia de datos
